/* Generated By:JJTree: Do not edit this line. ASTHead.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngine;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.parser.DecisionStatement;
import br.ufal.tci.parser.Head;

public class ASTHead extends SimpleNode {
	public ASTHead(int id) {
		super(id);
	}

	public ASTHead(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngine engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof DecisionStatement) {
			DecisionStatement statement = (DecisionStatement) data;
			Head head = new Head();
			head = (Head) visitor.visit(this, head, engine);

			statement.setHead(head);

			return statement;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=a7b21d10e80eb478c6183f14e4fc6eb8 (do not edit this
 * line)
 */
