/* Generated By:JJTree: Do not edit this line. ASTIfLocalAttributionOperator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngineIF;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.operator.relational.IfLocalAttributionOperator;
import br.ufal.tci.tmp.IfLocalAttribution;

public class ASTIfLocalAttributionOperator extends SimpleNode {
	public ASTIfLocalAttributionOperator(int id) {
		super(id);
	}

	public ASTIfLocalAttributionOperator(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngineIF engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof IfLocalAttribution) {
			IfLocalAttribution attribution = (IfLocalAttribution) data;
			IfLocalAttributionOperator operator = new IfLocalAttributionOperator();

			attribution.setOperator(operator);

			return attribution;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=776ba189d03e798eb8897aa6761a2f15 (do not edit this
 * line)
 */
