/* Generated By:JJTree: Do not edit this line. ASTIfLocalDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngine;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.factor.IfFactor;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.tmp.IfLocalDeclaration;

public class ASTIfLocalDeclaration extends SimpleNode {
	public ASTIfLocalDeclaration(int id) {
		super(id);
	}

	public ASTIfLocalDeclaration(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngine engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof IfFactor) {
			IfFactor factor = (IfFactor) data;
			IfLocalDeclaration declaration = new IfLocalDeclaration();
			declaration = (IfLocalDeclaration) visitor.visit(this, declaration,
					engine);

			factor.setDeclaration(declaration);

			return factor;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=d336ce8a8125213a920e53ab4180a1a5 (do not edit this
 * line)
 */
