/* Generated By:JJTree: Do not edit this line. ASTIfFactor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngine;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.factor.IfFactor;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.term.IfMoreTerms;
import br.ufal.tci.term.IfTerm;

public class ASTIfFactor extends SimpleNode {
	public ASTIfFactor(int id) {
		super(id);
	}

	public ASTIfFactor(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngine engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof IfTerm) {
			IfTerm term = (IfTerm) data;
			IfFactor factor = new IfFactor();
			factor = (IfFactor) visitor.visit(this, factor, engine);
			term.setFactor(factor);

			return term;

		} else if (data instanceof IfMoreTerms) {
			IfMoreTerms terms = (IfMoreTerms) data;
			IfFactor factor = new IfFactor();
			factor = (IfFactor) visitor.visit(this, factor, engine);

			terms.setFactor(factor);

			return terms;

		} else if (data instanceof IfFactor) {
			IfFactor factor = (IfFactor) data;
			IfFactor otherFactor = new IfFactor();
			otherFactor = (IfFactor) visitor.visit(this, otherFactor, engine);

			factor.setFactor(otherFactor);

			return factor;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=eed7bd9573968b14e574de6bacf6fb3a (do not edit this
 * line)
 */
