/* Generated By:JJTree: Do not edit this line. ASTRoot.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngineIF;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;

public class ASTRoot extends SimpleNode {
	public ASTRoot(int id) {
		super(id);
	}

	public ASTRoot(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngineIF engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=423e0ec074bfc3349b6bdfb6fb6f53ac (do not edit this
 * line)
 */
