/* Generated By:JJTree: Do not edit this line. ASTVariableList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngine;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.parser.VariableDeclaration;
import br.ufal.tci.parser.VariableList;

public class ASTVariableList extends SimpleNode {
	public ASTVariableList(int id) {
		super(id);
	}

	public ASTVariableList(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngine engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof VariableDeclaration) {
			VariableDeclaration variableDeclaration = (VariableDeclaration) data;
			VariableList variableList = new VariableList();
			variableList = (VariableList) visitor.visit(this, variableList,
					engine);

			variableDeclaration.addVariableList(variableList);

			return variableDeclaration;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=311fc72f83f12ed0fadca694cc939f67 (do not edit this
 * line)
 */
