/* Generated By:JavaCC: Do not edit this line. Parser_1TreeConstants.java Version 4.2 */
package br.ufal.tci.JJTREE;

public interface Parser_1TreeConstants
{
  public int JJTROOT = 0;
  public int JJTSTART = 1;
  public int JJTOBJECTINSTANCIATION = 2;
  public int JJTID = 3;
  public int JJTINTERVAL = 4;
  public int JJTLISTOFNUMBERS = 5;
  public int JJTARGUMENTLIST = 6;
  public int JJTINTEGER = 7;
  public int JJTFLOATPOINT = 8;
  public int JJTCHARACTERLITERAL = 9;
  public int JJTSTRINGLITERAL = 10;
  public int JJTARGUMENT = 11;
  public int JJTVARIABLEDECLARATION = 12;
  public int JJTVARIABLELIST = 13;
  public int JJTTYPE = 14;
  public int JJTCONSTANT = 15;
  public int JJTVARIABLE = 16;
  public int JJTIFRELATIONALOPERATOR = 17;
  public int JJTIFEXPRESSION = 18;
  public int JJTIFSIMPLEEXPRESSION = 19;
  public int JJTIFADDITIVEOPERATOR = 20;
  public int JJTIFMORESIMPLEEXPRESSION = 21;
  public int JJTIFTERM = 22;
  public int JJTMULTIPLICATIVEOPERATOR = 23;
  public int JJTIFMORETERMS = 24;
  public int JJTIFLOCALDECLARATION = 25;
  public int JJTIFLOCALATTRIBUTION = 26;
  public int JJTIFLOCALATTRIBUTIONOPERATOR = 27;
  public int JJTIFFACTOR = 28;
  public int JJTTHENRELATIONALOPERATOR = 29;
  public int JJTTHENEXPRESSION = 30;
  public int JJTTHENADDITIVEOPERATOR = 31;
  public int JJTTHENSIMPLEEXPRESSION = 32;
  public int JJTTHENMORESIMPLEEXPRESSION = 33;
  public int JJTTHENTERM = 34;
  public int JJTTHENMULTIPLICATIVEOPERATOR = 35;
  public int JJTTHENMORETERMS = 36;
  public int JJTTHENFACTOR = 37;
  public int JJTRULEDECLARATION = 38;
  public int JJTLISTOFRULES = 39;
  public int JJTRULE = 40;
  public int JJTDECISIONSTATEMENT = 41;
  public int JJTBODY = 42;
  public int JJTHEAD = 43;
  public int JJTCONCLUSIONLIST = 44;
  public int JJTCONCLUSION = 45;
  public int JJTFACTDECLARATION = 46;
  public int JJTLISTOFFACTS = 47;
  public int JJTFACT = 48;
  public int JJTMETHODINVOCATION = 49;
  public int JJTTHENINCLUSIVEOPERATOR = 50;
  public int JJTTHENATTRIBUTION = 51;
  public int JJTPROGRAM = 52;


  public String[] jjtNodeName = {
    "Root",
    "Start",
    "ObjectInstanciation",
    "ID",
    "Interval",
    "ListOfNumbers",
    "ArgumentList",
    "Integer",
    "FloatPoint",
    "CharacterLiteral",
    "StringLiteral",
    "Argument",
    "VariableDeclaration",
    "VariableList",
    "Type",
    "Constant",
    "Variable",
    "IfRelationalOperator",
    "IfExpression",
    "IfSimpleExpression",
    "IfAdditiveOperator",
    "IfMoreSimpleExpression",
    "IfTerm",
    "MultiplicativeOperator",
    "IfMoreTerms",
    "IfLocalDeclaration",
    "IfLocalAttribution",
    "IfLocalAttributionOperator",
    "IfFactor",
    "ThenRelationalOperator",
    "ThenExpression",
    "ThenAdditiveOperator",
    "ThenSimpleExpression",
    "ThenMoreSimpleExpression",
    "ThenTerm",
    "ThenMultiplicativeOperator",
    "ThenMoreTerms",
    "ThenFactor",
    "RuleDeclaration",
    "ListOfRules",
    "Rule",
    "DecisionStatement",
    "Body",
    "Head",
    "ConclusionList",
    "Conclusion",
    "FactDeclaration",
    "ListOfFacts",
    "Fact",
    "MethodInvocation",
    "ThenInclusiveOperator",
    "ThenAttribution",
    "Program",
  };
}
/* JavaCC - OriginalChecksum=906409a0875ca93012241a909744487f (do not edit this line) */
