/* Generated By:JJTree: Do not edit this line. ASTConclusionList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import java.util.LinkedList;
import java.util.List;

import br.ufal.tci.InferenceEngine.InferenceEngineIF;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.parser.Fact;
import br.ufal.tci.parser.Head;

public class ASTConclusionList extends SimpleNode {
	public ASTConclusionList(int id) {
		super(id);
	}

	public ASTConclusionList(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	@SuppressWarnings("unchecked")
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngineIF engine) throws SemanticException {

		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof Head) {
			Head head = (Head) data;
			List<Fact> list = (List<Fact>) visitor.visit(this,
					new LinkedList<Fact>(), engine);
			head.setConclusionList(list);
			return head;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=e85cdf719c7d9594a32de501bf061258 (do not edit this
 * line)
 */
