/* Generated By:JJTree: Do not edit this line. ASTListOfNumbers.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngineIF;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;

public class ASTListOfNumbers extends SimpleNode {
	public ASTListOfNumbers(int id) {
		super(id);
	}

	public ASTListOfNumbers(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngineIF engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=64d2d560a51b0dd4f98a050cd54761e9 (do not edit this
 * line)
 */
