/* Generated By:JJTree: Do not edit this line. ASTBody.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngine;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.parser.Body;
import br.ufal.tci.parser.DecisionStatement;

public class ASTBody extends SimpleNode {
	public ASTBody(int id) {
		super(id);
	}

	public ASTBody(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngine engine) throws SemanticException {

		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		
		if (data instanceof DecisionStatement) {

			DecisionStatement statement = (DecisionStatement) data;
			Body body = new Body();
			body = (Body) visitor.visit(this, body, engine);

			statement.setBody(body);

			return statement;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=90a97d3843e95393978286fc55db08ac (do not edit this
 * line)
 */
