/* Generated By:JJTree: Do not edit this line. ASTFloatPoint.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngineIF;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.parser.Argument;
import br.ufal.tci.parser.Constant;

public class ASTFloatPoint extends SimpleNode {

	public ASTFloatPoint(int id) {
		super(id);
	}

	public ASTFloatPoint(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngineIF engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof Argument) {
			Argument argument = (Argument) data;
			argument.addIdentifier(new Constant(Float
					.parseFloat(this.token.image)));
			return argument;
		}
		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=2f8690cee07e968509ccc459869b3b82 (do not edit this
 * line)
 */
