/* Generated By:JJTree: Do not edit this line. ASTFactDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngine;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.parser.FactDeclaration;
import br.ufal.tci.parser.Program;

public class ASTFactDeclaration extends SimpleNode {
	public ASTFactDeclaration(int id) {
		super(id);
	}

	public ASTFactDeclaration(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngine engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof Program) {
			Program program = Program.Instance();
			FactDeclaration factDeclaration = new FactDeclaration();
			factDeclaration = (FactDeclaration) visitor.visit(this,
					factDeclaration, engine);

			program.setFactDeclaration(factDeclaration);

			return program;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=7d7afc422277aa5fb6ebecf3bf593ec8 (do not edit this
 * line)
 */
