/* Generated By:JJTree: Do not edit this line. ASTIfSimpleExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngine;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.expression.IfExpression;
import br.ufal.tci.expression.IfSimpleExpression;
import br.ufal.tci.logger.LoggerGenerator;

public class ASTIfSimpleExpression extends SimpleNode {
	public ASTIfSimpleExpression(int id) {
		super(id);
	}

	public ASTIfSimpleExpression(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngine engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof IfExpression) {
			IfExpression expression = (IfExpression) data;
			IfSimpleExpression simple = new IfSimpleExpression();
			simple = (IfSimpleExpression) visitor.visit(this, simple, engine);
			expression.setSimpleExpression(simple);

			return expression;

		}
		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=042c24c87331aadbcfeb4ab2cdb7df1c (do not edit this
 * line)
 */
