/* Generated By:JJTree: Do not edit this line. ASTIfMoreSimpleExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngineIF;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.expression.IfMoreSimpleExpression;
import br.ufal.tci.expression.IfSimpleExpression;
import br.ufal.tci.logger.LoggerGenerator;

public class ASTIfMoreSimpleExpression extends SimpleNode {
	public ASTIfMoreSimpleExpression(int id) {
		super(id);
	}

	public ASTIfMoreSimpleExpression(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngineIF engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof IfSimpleExpression) {
			IfSimpleExpression expression = (IfSimpleExpression) data;
			IfMoreSimpleExpression mSimpleExpression = new IfMoreSimpleExpression();
			mSimpleExpression = (IfMoreSimpleExpression) visitor.visit(this,
					mSimpleExpression, engine);

			expression.setMoreSimpleExpression(mSimpleExpression);

			return expression;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=d3685c151714272e63c55c42d33f4226 (do not edit this
 * line)
 */
