/* Generated By:JJTree: Do not edit this line. ASTInterval.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngine;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.logger.LoggerGenerator;

public class ASTInterval extends SimpleNode {
	public ASTInterval(int id) {
		super(id);
	}

	public ASTInterval(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngine engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=aa1ab6b32a197728f34f078bc2d7575f (do not edit this
 * line)
 */
