/* Generated By:JJTree: Do not edit this line. ASTIfAdditiveOperator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngineIF;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.expression.IfMoreSimpleExpression;
import br.ufal.tci.expression.IfSimpleExpression;
import br.ufal.tci.logger.LoggerGenerator;
import br.ufal.tci.operator.additive.AdditiveOperator;
import br.ufal.tci.operator.additive.Minus;
import br.ufal.tci.operator.additive.Or;
import br.ufal.tci.operator.additive.Plus;

public class ASTIfAdditiveOperator extends SimpleNode {
	public ASTIfAdditiveOperator(int id) {
		super(id);
	}

	public ASTIfAdditiveOperator(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngineIF engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof IfSimpleExpression) {
			IfSimpleExpression expression = (IfSimpleExpression) data;
			AdditiveOperator operator = null;
			if (this.name.equalsIgnoreCase("+")) {
				operator = new Plus();
			} else if (this.name.equalsIgnoreCase("-")) {
				operator = new Minus();
			} else if (this.name.equalsIgnoreCase("or")) {
				operator = new Or();
			}
			expression.setOperator(operator);

			return expression;

		} else if (data instanceof IfMoreSimpleExpression) {
			IfMoreSimpleExpression expression = (IfMoreSimpleExpression) data;
			AdditiveOperator operator = null;
			if (this.name.equalsIgnoreCase("+")) {
				operator = new Plus();
			} else if (this.name.equalsIgnoreCase("-")) {
				operator = new Minus();
			} else if (this.name.equalsIgnoreCase("or")) {
				operator = new Or();
			}
			expression.setOperator(operator);

			return expression;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=411624a654928d7d682aff1ef31dc97e (do not edit this
 * line)
 */
