/* Generated By:JJTree: Do not edit this line. ASTThenMoreSimpleExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.ufal.tci.JJTREE;

import br.ufal.tci.InferenceEngine.InferenceEngine;
import br.ufal.tci.exception.SemanticException;
import br.ufal.tci.expression.ThenMoreSimpleExpression;
import br.ufal.tci.expression.ThenSimpleExpression;
import br.ufal.tci.logger.LoggerGenerator;

public class ASTThenMoreSimpleExpression extends SimpleNode {
	public ASTThenMoreSimpleExpression(int id) {
		super(id);
	}

	public ASTThenMoreSimpleExpression(Parser_1 p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(Parser_1Visitor visitor, Object data,
			InferenceEngine engine) throws SemanticException {
		LoggerGenerator.debug("Visitando " + this.getClass().getCanonicalName());
		if (data instanceof ThenSimpleExpression) {
			ThenSimpleExpression simpleExpression = (ThenSimpleExpression) data;
			ThenMoreSimpleExpression moreSimpleExpression = new ThenMoreSimpleExpression();
			moreSimpleExpression = (ThenMoreSimpleExpression) visitor.visit(
					this, moreSimpleExpression, engine);
			simpleExpression.setMoreSimpleExpression(moreSimpleExpression);
			return simpleExpression;
		}

		return visitor.visit(this, data, engine);
	}
}
/*
 * JavaCC - OriginalChecksum=2d8499290d62761225b3a709375f7bd3 (do not edit this
 * line)
 */
